name: money_tracker
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_cli: ^1.9.1
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  flutter_svg: ^2.2.1
  dotted_border: ^3.1.0

  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  advanced_salomon_bottom_bar: ^3.3.4

  intl: ^0.20.2
  shared_preferences: ^2.5.3
  google_sign_in: ^7.1.1
  flutter_spinkit: ^5.2.2
  animated_custom_dropdown: ^3.1.1

  image_picker: ^1.2.0
  cached_network_image: ^3.4.1
  file_picker: ^10.3.3
  shimmer: ^3.0.0
  url_launcher: ^6.3.2
  syncfusion_flutter_charts: ^31.1.21

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset : assets/fonts/Montserrat-Bold.ttf
          weight: 700

